name = "STCounterexampleCheck"
uuid = "a41c45f5-48fd-409d-8b15-c5ffb6594edb"
version = "0.1.0"
authors = ["KentaroKajiyama <kemushi555@icloud.com>"]

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
GraphIO = "aa1b3936-2fda-51b9-ab35-c553d3a640a2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MsgPack = "99f44e22-a591-53d1-9472-aa23ef4bd671"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
ArgParse = "1.2.0"
Combinatorics = "1.0.3"
GraphIO = "0.7.1"
Graphs = "1.13.1"
JSON = "1.3.0"
LinearAlgebra = "1.12.0"
MsgPack = "1.2.1"
Nemo = "0.52.3"
Primes = "0.5.7"
Random = "1.11.0"
